name: Recreate README

on:
  workflow_run:
    workflows:
      - Build @kasefuchs/readme
    types:
      - completed
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout main
        uses: actions/checkout@master
        with:
          ref: 'main'
          path: 'main'

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: build-readme.yml
            workflow_conclusion: success
            name: readme-generator
            check_artifacts: true
            path: readme-downloader

      - name: Recreate README
        run: |
          cd $GITHUB_WORKSPACE/readme-downloader
          node ./index.js
          cp generated/**/* $GITHUB_WORKSPACE/main

      - name: Push README
        run: |
          cd $GITHUB_WORKSPACE/main
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push

  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'